#!/usr/bin/env bash
# installs with the following configurations:
#+  Enables management via the init script.
#+  Distributes requests using a round-robin algorithm
# Update package lists
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cat << EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [519604-web-01]-34.232.52.151:80 check
    server web-02 [519604-web-01]-54.174.21.162:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

sudo hostnamectl set-hostname [519604-lb-01]-lb-01

echo "HAProxy installed and configured successfully."

