#!/bin/env bash

# Stop any services already running on port 80
sudo systemctl stop apache2

# Modify Nginx configuration to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
