#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# "bad luck from China" at the 4th iteration
# "bad luck from Japan" at the 9th iteration
# "bad luck from Italy" at the 17th loop iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
