#!/bin/bash

# Get the PID of the Gunicorn master process
MASTER_PID=$(ps aux | grep gunicorn | grep master | awk '{print $2}')

# If Gunicorn is running, send the HUP signal to the master process
if [ -n "$MASTER_PID" ]; then
    echo "Reloading Gunicorn..."
    kill -HUP $MASTER_PID
    echo "Gunicorn has been reloaded!"
else
    echo "Gunicorn is not running."
fi

